#Este arquivo constroi os conteiner a partir de imagens: Jenkins (contendo o job criado), SonarQube e Nexus armazenados no DockerHub que pode acessado em:
#https://hub.docker.com/repository/docker/larissasouzapinto/task2
#Este documento faz parte da TASK2 do desafio proposto em:https://github.com/jfsc/CDPIPELINE
version: '2'
services:
  nginx-nexusproxy:
    image: larissasouzapinto/task2:jobjenkins_nginx
    ports:
      - "443:443"
      - "8082:8082"
      - "8083:8083"
    links:
      - nexus-repo
    command: [ nginx, '-g', 'daemon off;' ]
  
  nexus-repo:
    image: larissasouzapinto/task2:jobjenkins_nexus
    container_name: nexus
    ports:
      - "8081:8081"
    volumes:
      - /some/dir/nexus-data:/nexus-data sonatype/nexus3

  jenkins:
    image: larissasouzapinto/task2:jobjenkins
    privileged: true
    user: root
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
  
  sonarqube:
    image: larissasouzapinto/task2:jobjenkins_sonarqube
    container_name: sonarqube
    restart: always
    ports:
    - "9000:9000"
    depends_on:
      - sonardb
    links:
      - sonardb
    environment:
    - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
    - SONARQUBE_JDBC_USERNAME=sonar
    - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - "/opt/sonar/:/var/lib/sonar"

  sonardb:
    image: larissasouzapinto/task2:jobjenkins_postgres
    container_name: postgres
    restart: always
    environment:
    - POSTGRES_USER=sonar
    - POSTGRES_PASSWORD=sonar
    - POSTGRESQL_DB=sonar
    ports:
      - "5432:5432"