FROM jenkins/jenkins:lts
USER root
RUN apt-get update && \
apt-get -y install apt-transport-https \
    ca-certificates \
    curl \
    gnupg2 \
    software-properties-common && \
curl -fsSL https://get.docker.com -o get-docker.sh \
curl -fsSL https://test.docker.com -o test-docker.sh \
echo "$ID")/gpg > /tmp/dkey; apt-key add /tmp/dkey && \
add-apt-repository \
    "deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") \
    $(lsb_release -cs) \
    stable" && \
apt-get update && \
RUN sh get-docker.sh \
RUN sh test-docker.sh \
RUN cd .. \
COPY --chown=jenkins:jenkins Task2 /var/jenkins_home/workspace/  